# Generated by Django 3.2.9 on 2022-01-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
